In [19]:
import pandas as pd
import numpy as np

In [2]:
# Load dataset
excel_file = 'online+retail+ii/online_retail_II.xlsx'
sheets = pd.read_excel(excel_file, sheet_name=None)
# Combine sheets
df_raw = pd.concat(sheets.values(), ignore_index=True)
df_raw.to_csv('online+retail+ii/online_retail_II.csv', index=False)

Inspect dataframe

In [4]:
df_raw.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [5]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[ns]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 65.1+ MB

In [6]:
df_raw.dtypes

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID           float64
Country                object
dtype: object

In [7]:
df_raw.describe

<bound method NDFrame.describe of         Invoice StockCode                          Description  Quantity  \
0        489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12
1        489434    79323P                   PINK CHERRY LIGHTS        12
2        489434    79323W                  WHITE CHERRY LIGHTS        12
3        489434     22041         RECORD FRAME 7" SINGLE SIZE         48
4        489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24
...         ...       ...                                  ...       ...
1067366  581587     22899         CHILDREN'S APRON DOLLY GIRL          6
1067367  581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
1067368  581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
1067369  581587     22138        BAKING SET 9 PIECE RETROSPOT          3
1067370  581587      POST                              POSTAGE         1

                InvoiceDate  Price  Customer ID         Country
0       2009-12-01 07:45:00   6.95      13085.0  United Kingdom
1       2009-12-01 07:45:00   6.75      13085.0  United Kingdom
2       2009-12-01 07:45:00   6.75      13085.0  United Kingdom
3       2009-12-01 07:45:00   2.10      13085.0  United Kingdom
4       2009-12-01 07:45:00   1.25      13085.0  United Kingdom
...                     ...    ...          ...             ...
1067366 2011-12-09 12:50:00   2.10      12680.0          France
1067367 2011-12-09 12:50:00   4.15      12680.0          France
1067368 2011-12-09 12:50:00   4.15      12680.0          France
1067369 2011-12-09 12:50:00   4.95      12680.0          France
1067370 2011-12-09 12:50:00  18.00      12680.0          France

[1067371 rows x 8 columns]>

In [8]:
# Check duplicates
df_raw.duplicated().sum()

34335

In [9]:
# Check Missing values
df_raw.isna().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [10]:
df_raw[df_raw['Description'].isna()]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
1060783,581199,84581,NaN,-2,2011-12-07 18:26:00,0.0,NaN,United Kingdom
1060787,581203,23406,NaN,15,2011-12-07 18:31:00,0.0,NaN,United Kingdom
1060793,581209,21620,NaN,6,2011-12-07 18:35:00,0.0,NaN,United Kingdom
1062442,581234,72817,NaN,27,2011-12-08 10:33:00,0.0,NaN,United Kingdom
1064015,581408,85175,NaN,20,2011-12-08 14:06:00,0.0,NaN,United Kingdom

In [11]:
df_raw[df_raw['Customer ID'].isna()]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.00,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.00,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.00,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.00,NaN,United Kingdom
577,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
1066997,581498,85099B,JUMBO BAG RED RETROSPOT,5,2011-12-09 10:26:00,4.13,NaN,United Kingdom
1066998,581498,85099C,JUMBO BAG BAROQUE BLACK WHITE,4,2011-12-09 10:26:00,4.13,NaN,United Kingdom
1066999,581498,85150,LADIES & GENTLEMEN METAL SIGN,1,2011-12-09 10:26:00,4.96,NaN,United Kingdom
1067000,581498,85174,S/4 CACTI CANDLES,1,2011-12-09 10:26:00,10.79,NaN,United Kingdom
1067001,581498,DOT,DOTCOM POSTAGE,1,2011-12-09 10:26:00,1714.17,NaN,United Kingdom

Cleaning

In [34]:
# Create a copy 
df = df_raw.copy()

In [36]:
# Standardize Columns 
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df = df.rename(columns={"invoicedate": "invoice_date", "stockcode": "stock_code"})

In [38]:
# Drop rows with missing customer id
df = df.dropna(subset=['customer_id'])

In [40]:
# Filter out rows with negative quantity
df = df[df['quantity'] > 0]

In [52]:
# Filter our rows with negative or 0 price
df = df[df['price'] > 0]

In [60]:
# Fix data types
# customer_id from float to string
df.loc[:,'customer_id'] = df['customer_id'].astype(int).astype(str)

In [76]:
# Create total price column
df.loc[:, 'total_price'] = df['quantity'] * df['price']

In [80]:
df.head()

,invoice,stock_code,description,quantity,invoice_date,price,customer_id,country,total_price
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0

In [86]:
# Check for irregular stock codes 
import re
weird_codes = df[df['stock_code'].astype(str).str.contains(r'^[A-Za-z]+$')]['stock_code'].unique()
print(weird_codes)

['POST' 'M' 'PADS' 'ADJUST' 'D' 'DOT']

In [94]:
# Filter out irregular stock codes
irregular_codes = ['POST' 'M' 'PADS' 'ADJUST' 'D' 'DOT']
df = df[~df['stock_code'].isin(irregular_codes)]

In [96]:
print(f"Cleaned row count: {df.shape[0]}")
print("Data cleaning complete.")

Cleaned row count: 805549
Data cleaning complete.